dataset:
  type: train
  data_root_path: ../data/rsna-2022-cervical-spine-fracture-detection/
  train_3d_images: ../data/3d_train_images_v4/
#  train_segmentations_path: ../semantic_segmentation/predicted_data3/uint8/fold0/

  common_shape_for_bb: [null, 256, 256]
  cropped_2d_labels_path: ../data/cropped_2d_labels/new_cropped_2d_labels.csv

#  semantic_segmentation_bb_path: ../semantic_segmentation/models/UNet_128x256x256/semantic_segmentation_bb/train_semantic_segmentation_bb_fold0.csv
#  cropped_2d_images_path: ../data/cropped_2d_images
  semantic_segmentation_bb_path: ../semantic_segmentation/models/UNet_256x256x256/semantic_segmentation_bb/train_semantic_segmentation_bb_fold0.csv
  cropped_2d_images_path: ../data/cropped_2d_images/UNet_256x256x256

  use_segmentation: false

#  data_type: u1
  data_type: f4

  enable_depth_resized_with_cv2: true

  type_to_load: npz
#  type_to_load: dcm

  use_normalized_batches: true
  use_windowing: true

  target_columns: [patient_overall, C1, C2, C3, C4, C5, C6, C7]
  cv:
    type: StratifiedKFold
    seed: 42
    n_folds: 4
    fold: null  # null -> run all folds for monai/run.py

#  num_workers: null  # null -> os.cpu_count()
  num_workers: 4
  train_batch_size: 32
  valid_batch_size: 64
  test_batch_size: 2

  train_cache_rate: 0
  valid_cache_rate: 0


model:
  seed: 42
#  name: EfficientNetBN
#  kwargs:
#    model_name: efficientnet-b0
#    in_channels: 1
#    pretrained: true
  name: SEResNext50
  kwargs:
    in_channels: 1

  spatial_dims: 2
  use_multi_sample_dropout: false

  optimizer:
    name: AdamW
    scheduler:
#      name: null
#      name: cosine
#      kwargs:
#        num_warmup_steps: 100
#        num_training_steps: 500
#      name: MultiStep
#      kwargs:
#        milestones: [300]f
#        gamma: 1e-3
      name: CosineAnnealingWarmRestarts
      kwargs:
        T_0: 700
        T_mult: 1
        eta_min: 1e-9


train:
  accelerator: gpu
  devices: 1

  precision: 16

  seed: 42

  max_epochs: 80

  learning_rate: 1e-4
  weight_decay: 0
  name_prefix: ""

  name_suffix: v5.4.3

  model_path: models/test

  early_stopping: false

  validation_interval: 0.1
  evaluate_after_steps: 0

  logging_interval: 1

#  augmentation:
#    scale_intensity:
#      kwargs:
#        factors: [-0.2, 0.2]
#        prob: 0.5
#    shift_intensity:
#      kwargs:
#        offsets: [-0.1, 0.1]
#        prob: 0.5
#    affine:
#      rotate_range_in_deg: [15, 0, 0]
#      translate_range_in_scale: [0, 0.0625, 0.0625]
#      kwargs:
#        prob: 0.5
#        scale_range: [0, 0.1, 0.1]
#        mode: nearest
#        padding_mode: reflection
