dataset:
  type: train
  data_root_path: /home/jumpei.uchida/develop/data/rsna
  train_3d_images: ../data/3d_train_images

  target_columns: [patient_overall, C1, C2, C3, C4, C5, C6, C7]
  cv:
    type: KFold
    seed: 42
    n_folds: 2
    fold: 0  # null -> run all folds for monai/run.py

  num_workers: null  # null -> os.cpu_count()
  train_batch_size: 2
  valid_batch_size: 2
  test_batch_size: 2

  depth: 128

model:
  seed: 42
  name: resnet10
  kwargs:
     n_input_channels: 1

  optimizer:
    name: AdamW
    scheduler:
#      name: null
      name: cosine
      num_warmup_steps: 50
      num_training_steps: 10000


train:
  accelerator: gpu
  devices: 1

  precision: 16

  seed: 42

  max_epochs: 5

  learning_rate: 1e-4
  weight_decay: 0
  name_suffix: test
  model_path: models

  validation_interval: 0.2
  evaluate_after_steps: 0

  logging_interval: 1