dataset:
  type: train
  data_root_path: ../data/rsna-2022-cervical-spine-fracture-detection/
  train_3d_images: ../data/3d_train_images_v4/
  cropped_2d_labels_path: null
  cropped_2d_images_path: null

  common_shape_for_bb: [41, 122, 142]

  use_segmentation: false  # will be true if needed in the code
  train_segmentations_path: null  # will be replaced in the code

#  type_to_load: npz
#  type_to_load: dcm

  use_windowing: true

  target_columns: [patient_overall, C1, C2, C3, C4, C5, C6, C7]
  cv:
    type: StratifiedKFold
    seed: 42
    n_folds: 4
    fold: null  # null -> run all folds for monai/run.py
