data:
  RSNA_2022_PATH: '/home/jumpei.uchida/develop/data/rsna'
  EFFNET_CHECKPOINTS_PATH: '../../src/saved_model/effnet'
  METADATA_PATH: '/home/jumpei.uchida/develop/data/rsna/metadata'

model:
  BATCH_SIZE: 32
  EFFNET_MAX_TRAIN_BATCHES: 10000
  EFFNET_MAX_EVAL_BATCHES: 200
  ONE_CYCLE_MAX_LR: 0.0001
  ONE_CYCLE_PCT_START: 0.3
  ONE_CYCLE_EPOCH: 1
  SAVE_CHECKPOINT_EVERY_STEP: 100
  FRAC_LOSS_WEIGHT: 2
  N_FOLDS: 3
  PREDICT_MAX_BATCHES: 1000000000000
  SEED: 42

base:
  PROJECT_NAME: "RSNA_binary"
  MODEL_NAME: "effnet_first"
