dataset:
  type: train
  data_root_path: ../data/rsna-2022-cervical-spine-fracture-detection
  train_3d_images: ../data/3d_train_images

  target_columns: [patient_overall, C1, C2, C3, C4, C5, C6, C7]
  cv:
    type: KFold
    seed: 42
    n_folds: 2
    fold: null  # null -> run all folds for monai/run.py

  num_workers: null  # null -> os.cpu_count()
  train_batch_size: 4
  valid_batch_size: 4
  test_batch_size: 2

  depth: 128

model:
  seed: 42
  name: EfficientNetBN
  kwargs:
    model_name: efficientnet-b3
    in_channels: 1
    pretrained: true

  use_multi_sample_dropout: true

  optimizer:
    name: AdamW
    scheduler:
      name: null
#      name: linear
#      num_warmup_steps: 500
#      num_training_steps: 2100


train:
  accelerator: gpu
  devices: 1

  precision: 16

  seed: 42

  max_epochs: 4

  learning_rate: 1e-4
  weight_decay: 0
  name_prefix: ""
  name_suffix: test-v13
  model_path: models

  early_stopping: true

  validation_interval: 0.2
  evaluate_after_steps: 0

  logging_interval: 1